[mdzk]
authors = ["Carlo Veronesi"]
language = "en"
multilingual = false
src = "notes"
title = "GCP notes"

[build]
create-missing=false

[output.html.fold]
enable = true

[output.html.search]
enable = true