name: CI-mdzk

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install mdzk
        uses: actions-rs/install@v0.1.2
        with:
          crate: mdzk
          version: latest

      - name: Build ZK
        run: mdzk build
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: html # The folder the action should deploy.
